BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls"))
]

blog/urls.py
from django.urls import path
from . import views

app_name ="blog"

urlpatterns = [
    path("", views.home.as_view(), name="home"),
    path("about/", views.aboutView, name="about"),
    path("blog/", views.post_list, name="list"),
    path("blog/<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail, name='post_detail'),
    path("<int:post_id>/comment",views.post_comment, name="post_comment"),
    path('tag/<slug:tag_slug>/',
        views.post_list, name='post_list_by_tag'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager
from django.urls import reverse
import pytz


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Post.Status.PUBLISHED)
    
    
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"
    title = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField()
    status = models.CharField(max_length=2
                                ,choices=Status.choices,
                                default=Status.DRAFT)
    publish = models.DateTimeField(default=timezone.datetime.now(pytz.timezone("Asia/Tokyo")))
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    
    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"])
        ]
    
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
                        self.publish.year,
                        self.publish.month,
                        self.publish.day,
                        self.slug
                        ])


class Comment(models.Model):
    post = models.ForeignKey(Post, 
                            on_delete=models.CASCADE,
                            related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"])
        ]
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

class developManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=developed.Status.PUBLISHED)

class developed(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"
    image = models.ImageField()
    body = models.TextField()
    publish = models.CharField(max_length=2,
                                choices=Status.choices,
                                default=Status.DRAFT)
    Published = developManager()

class FormModel(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    enquiry = models.TextField()
    def __str__(self) -> str:
        return f"from {self.name}"

blog/forms.py
from django import forms
from .models import Comment, FormModel

class aboutForm(forms.ModelForm):
    # name = forms.CharField(max_length=30)
    # email = forms.EmailField()
    # enquiry = forms.CharField(required=True,
    #                         widget=forms.Textarea)
    class Meta:
        model = FormModel
        fields = "__all__"

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]
                

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic.base import TemplateView
from django.views import generic
from django.urls import reverse_lazy
from django.core.mail import send_mail
from . import forms
from . import models
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage,\
    PageNotAnInteger

# Create your views here.

class home(TemplateView):
    template_name = "blog/home.html"


def aboutView(request):
    sent = False
    if request.method == "POST":
        form = forms.aboutForm(request.POST)
        if form.is_valid():
            form.save()
            cd = form.cleaned_data
            subject = "Kato's siteから"
            message = "フォームの利用ありがとうございます。"
            send_mail(subject, message, "katopillow@gmail.com", [cd["email"]])
            sent = True
    else:
        form = forms.aboutForm()
    return render(request, "blog/about.html", context={
        "form": form,
        "sent": sent
    })

def post_detail(request, year, month, day, post):
    post = get_object_or_404(models.Post,
    status=models.Post.Status.PUBLISHED,
    slug=post,
    publish__year=year,
    publish__month=month,
    publish__day=day)
    comment = post.comments.filter(active=True)
    form = forms.CommentForm()
    return render(request,
                    'blog/detail.html',context={
                    'post': post, 
                    "comment": comment,
                    "form": form
                    })
    
class PostListView(generic.ListView):
    queryset = models.Post.published.all()
    context_object_name = "posts"
    paginate_by = 5
    template_name = "blog/list.html"


def post_list(request, tag_slug=None):
    post_lists = models.Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_lists = post_lists.filter(tags__in=[tag])
    paginator = Paginator(post_lists, 5)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
    # If page_number is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                    'blog/list.html',
                    {'posts': posts,
                    'tag': tag})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(models.Post, id=post_id,
                        status=models.Post.Status.PUBLISHED)
    comment = None
    form = forms.CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, "blog/comment.html",
                context={
                    "post": post,
                    "form": form,
                    "comment": comment
                })

templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% load widget_tweaks  %}

{% block title %}about{% endblock title %}

{% block content %}


{% if sent %}
  <div class="container text-center mt-5">
    <h1>お問い合わせありがとうございます</h1>
  </div><!-- /.container text-center -->
{% else %}
<div class="container mt-4" >
  <div class="row justify-content-center pt-4">
    <div class="col-md-4 mt-4">
      <div class="card card-body bg-secondary text-dark" style="max-width: 25rem;">
        <h3 class="card-title py-2">
          &nbsp;plofile
        </h3><!-- /.card-title -->
        <p class="card-text mt-4" style="color:#191f1f">
          電子工学科卒<br>
          現在、情報科学専攻　修士1年<br><br>
          ソフトウェア開発と自然言語処理に興味がある。<br>
          車輪の再開発が好き

        </p><!-- /.card-text -->
        <img src="{% static 'img/leaf.jpg' %}" alt="leaf">
      </div><!-- /.card card-body -->
    </div><!-- /.col-5 -->
    
    <div class="col-md-4 mt-4">
      <div class="card bg-secondary text-dark" style="max-width: 25rem;">
        <img src="{% static 'img/pc.png' %}" alt="pc" class="card-img-top">
        <div class="crad-body text-center">
          <h4 class="card-title">
            SNS
          </h4><!-- /.card-title text-center -->
          <div class="col">
            <a href="https://twitter.com/shirousaGo" target="_brank">
              <img src="{% static 'img/twitter.svg' %}" alt="twitter" width="40" height="40" class="mx-3">
            </a>
            <a href="https://github.com/sirousagisan" target="_brank">
              <img src="{% static 'img/github.svg' %}" alt="github" height="37" width="37"class="mx-3">
            </a>
          </div><!-- /.col -->
        </div><!-- /.crad-body -->
      </div><!-- /.card -->
    </div><!-- /.col-4 -->

    <div class="col-md-4 mt-4">
      <div class="card card-body bg-secondary text-dark">
      <h1 class="mt-5">
        contact
      </h1><!-- /.mt-5 -->
      <form method="POST">
        {% for field in form %}

        <label for="{{ field.id_for_label}}" class="form-label mt-2">{{ field.label }} </label><br><!-- /.form-label -->
        {{ field|add_class:"form-control"}} <br>

        {% endfor %}
        {% csrf_token %}
        <div class="text-end ">
          <button class="btn btn-primary" type="submit" disabled>SNSまでお願いします</button>
        </div><!-- /.text-end -->
        
      </form>
    </div><!-- /.col align-self-center -->
      </div><!-- /.card card-body -->
      
  </div><!-- /.row -->


</div><!-- /.container -->


{% endif %}


{% endblock content %}

templates/blog/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang='ja'>

<head>
  <title>shirousagisan's site | {% block title %}{% endblock title %}</title>
  <meta charset='utf-8'>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>



<header class="py-2">

  <div class="container text-center">
    <a href="{% url 'blog:home' %}">
      <img src="{% static 'img/usagi_kaeru.svg' %}" alt="top" class="mw-100 img-responsive" height="70px">
    </a>
  </div><!-- /.h50 -->

</header><!-- /.py-2 -->

<nav class="navbar navbar-expand-md navbar-dark bg-secondary sticky-top">
  <!-- サブコンポーネント -->
  <div class="container">
    <!-- ブランド -->
    <a class="navbar-brand" href="{% url 'blog:home' %}">shirousagisan's site</a>
    <!-- 切り替えボタン -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- ナビゲーション -->
    <div class="collapse navbar-collapse" id="navbar-content">
      <!-- ナビゲーションメニュー -->
      <!-- 左側メニュー：トップページの各コンテンツへのリンク -->
      <ul class="navbar-nav ms-auto ">
        <li class="nav-item active ">
          <a class="nav-link" href="#">  <span class="visually-hidden">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:list' %}">blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">develop  </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:about' %}">about </a>
        </li>
        
      </ul>
      <!-- 右側メニュー：お問い合わせページへのリンク -->
      {% comment %} 
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="contact.html" class="nav-link btn btn-info text-dark">お問い合わせ</a>
        </li>
      </ul>
      {% endcomment %}
          <!-- /ナビゲーションメニュー -->
    </div>
  </div>
  <!-- /サブコンポーネント -->
</nav>



<body class="bg-dark text-white">
  {% block content %}
  {% endblock content %}
</body>

<footer class="py-4">

</footer><!-- /.py-4 -->


</html>

templates/blog/comment.html
{% extends 'blog/base.html' %}

{% block title %}Add a comment{% endblock title %}

{% block content %}
  {% if comment %}
    <div class="container pt-5">
      <div class="row justify-content-center mt-5">
        <div class="col-md-6">
          <h2>Your comment has been added.</h2>
          <p class="pt-3 text-center"><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
        </div><!-- /.col-md-6 -->
      </div><!-- /.row justify-content-center -->
    </div><!-- /.container -->
  {% else %}
  {% include "comment_form.html" %}
  {% endif %}

{% endblock content %}

templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}


{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8" >
      <h1 style="color: #00bfff">{{ post.title }}</h1>
      <p class="date" style="color:#ccd5db">
      Published {{ post.publish }} <br>
      tags: 
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}" style="color:#00ced1">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
      </p>
      
      {{ post.body|markdown|truncatewords_html:30 }}
      
    </div><!-- /.col -->
  </div><!-- /.row -->


  {% with comment.count as total_comment %}
    <div class="container mt-4">
      <div class="row justify-content-center pt-5">
        <div class="col-md-8">
          <h2>
            {{ total_comment }} comment{{ total_comment|pluralize}}
          </h2>
        </div><!-- /.col-md-8 -->
      </div><!-- /.row justify-content-center -->
    </div><!-- /.container mt-4 -->
  {% endwith %}
    
  {% for cmt in comment %}
  <div class="container mt-3">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card card-body bg-secondary text-dark">
          <p>
            comment {{ forloop.counter }} by {{ cmt.name }} <br>
            ~{{ cmt.created }}~
          </p>
          {{ cmt.body|linebreaks }}
        </div><!-- /.card card-body bg-secondary text-dark -->
      </div><!-- /.col-md-8 -->
    </div><!-- /.row justify-content-center -->
  </div><!-- /.container mt-3 -->
  {% endfor %}

  <div class="row justify-content-center mt-5">
    <div class="col-md-8 mt-5">
      <div class="card card-body text-dark bg-secondary">
        {% include "comment_form.html" %}
      </div><!-- /.card card-body text-dark -->
    </div><!-- /.col-md-4 -->
  </div><!-- /.row content-self-center -->


</div><!-- /.container -->




{% endblock content %}

templates/blog/home.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block title %}home{% endblock title %}

{% block content %}

<div class="py-4">
  <div class="container">
    <!-- carousel-->
    <div class="carousel slide" data-interval="500"  id="main_visual" data-bs-ride="carousel">
      <!-- indicator -->
      <ol class="carousel-indicators">
        <li data-bs-target="#main_visual" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#main_visual" data-bs-slide-to="1"></li>
        <li data-bs-target="#main_visual" data-bs-slide-to="2"></li>
      </ol>
      <!-- / インジケーター -->
      <!-- カルーセル内枠 -->
      <div class="carousel-inner" >
        <!-- スライド01 -->
        <div class="carousel-item active">
          <img class="img-fluid w-100" src="static/img/bike.jpg" alt="bike">
          
        </div>
        <!-- / スライド01 -->
        <!-- スライド02 -->
        <div class="carousel-item">
          <img class="img-fluid w-100" src="static/img/pc.jpg" alt="pc">
        </div>
        <!-- / スライド02 -->
        <!-- スライド03 -->
        <div class="carousel-item ">
          <img class="img-fluid w-100" src="static/img/load.jpg" alt="load">
          
        </div>
        <!-- / スライド03 -->
      </div>
    <!-- controler -->
    
      <a class="carousel-control-prev" href="#main_visual" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">前に戻る</span>
      </a>
      <a class="carousel-control-next" href="#main_visual" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">次に進む</span>
      </a>
    <!-- /controler -->
    </div><!-- /#main_visual.carousel slide -->
  </div><!-- /.container -->
</div><!-- /.py-2 -->

<div class="container">
  <h2 class="text-center" style="color:#ccd1e0"><br>
    ぱいそぉんでWeb系であったりディープラーニングであったり...
  </h2><!-- /.text-center -->

  <div class="row">
    <div class="col-10 col-md-7">
      <p class="mt-4 text-wrap" style="color:#c2cae0"><br><br>
        使える：<br>
        Python(Django, Pytorch, Transformers) <br>
        Typescript(Vue) <br>
        bootstrap <br>
        勉強中：<br>
        Rust,Go,<br>
        実務経験あり：<br>
        Python,Vue,leaflet,aws(boto3)

      </p>
    </div><!-- /.col -->
    <div class="col">
      <img src="static/img/sad.png" alt="sad" class="img-fluid">
    </div><!-- /.col -->
  </div><!-- /.row -->

</div><!-- /.container -->

{% endblock content %}

templates/blog/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}" style="color:#191970">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load static %}

{% block title %}My Blog{% endblock %}

{% block content %}

<div class="container">
  <h1 class="py-4">My Blog</h1>
  {% if tag %}
    <h2>
      Post tagged with "{{ tag.name }}"
    </h2>
  {% endif %}
<div class="container">
  <div class="row">  
    <div class="col-9">
      {% for post in posts %}
<div class="card mb-3 card-body bg-secondary position-relative" style="max-width: 50rem;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{% static 'img/leaf.jpg' %}" alt="..." width="200px" height="200px">

    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h3 class="card-title">
          <a href="{{ post.get_absolute_url}}" style="color:#191970" class="stretched-link">
            {{ post.title }}
          </a></h3><p class="card-text text-black">{{ post.publish }}</p>
          <p>
          Tags:
          {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}" style="color:#191970" class="stretched-link position-relative">
              {{ tag.name }}
            </a>
          {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>

        <p class="card-text">{{ post.body|markdown|truncatewords:0|linebreaks}}</p>
      </div>
    </div>
  </div>
</div>






      {% endfor %}
      <div class="row justify-content-center">
        <div class="col-6 mt-5">
          {% include "paginator3.html" with items_page=posts %}
        </div><!-- /.col -->
      </div><!-- /.row justify-content-center -->
        
        
    </div><!-- /.col -->
      
    <div class="col-1 d-none d-md-block text-black">
      <div class="sticky-top py-5" >
        <div class="card card-body bg-secondary mt-4" style="width: 20rem;">
          <h1 class="px-3 pt-4">My Blog</h1>
          <p class="px-3">I've written {% total_posts %} posts so far<p>
            <h5>Latest Posts</h5>
            {% show_latest_posts %}
              
          <h5>Most commented posts</h5>
          {% get_most_commented_posts as most_comments_posts %}
          <ul>
            {% for post in most_comments_posts %}
              <li>
                <a href="{{ post.get_absolute_url }}"style="color:#191970">{{ post.title }}</a>
              </li>
            {% endfor %}
          </ul>
        </div><!-- /.card card-body bg-secondary -->
      </div>
    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.container -->



{% endblock content %}

templates/comment_form.html
{% load widget_tweaks  %}
<h2>こめんとのカキコ</h2>

<form method="post" action="{% url 'blog:post_comment' post.id %}">
  {% csrf_token %}
  {% for field in form %}
    <label for="{{ field.id_for_label}}" class="form-label mt-2">{{ field.label }} </label><br><!-- /.form-label -->
    {{ field|add_class:"form-control"}} <br>
  {% endfor %}
  
  <div class="text-end ">
    <button class="btn btn-primary" type="submit" >送信する</button>
  </div><!-- /.text-end -->
</form>

templates/paginator.html
<div class="paginator">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Next</a>
    {% endif %}
    
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages}}.
    </span>
    
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    
  </span>
</div>

templates/paginator2.html
{% if page_obj %}
  <ul class="pagination">
    <!-- 前へ の部分 -->
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% endif %}

      <!-- 数字の部分 -->
    {% for num in page.paginator.page_range %}
      {% if page.number == num %}
        <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
      {% endif %}
    {% endfor %}

      <!-- 次へ の部分 -->
    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/paginator3.html
{% if items_page %}
    {% if items_page.has_other_pages %}
    <div class="btn-group" role="group" aria-label="Item pagination">
        {% if items_page.has_previous %}
            <a href="?page={{ items_page.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
        {% endif %}

        {% for page_number in items_page.paginator.page_range %}
            {% if items_page.number == page_number %}
                <button class="btn btn-outline-primary active">
                    <span>{{ page_number }} <span class="sr-only">(current)</span></span>
                </button>
            {% else %}
                <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                    {{ page_number }}
                </a>
            {% endif %}
        {% endfor %}

        {% if items_page.has_next %}
            <a href="?page={{ items_page.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
        {% endif %}
    </div>
    {% endif %}
{% else %}
    <p>No items found.</p>
{% endif %}